house.data.csv <- read.csv("household_power_consumption.txt", sep =";", na.strings="?")
house.data.csv$Date_as_Date <- as.Date(house.data.csv$Date, "%d/%m/%Y")
house.subset <- subset(house.data.csv, house.data.csv$Date_as_Date == as.Date("2007/02/01") | house.data.csv$Date_as_Date == as.Date("2007/02/02"))
house.subset$DateTime <- paste(house.subset$Date, house.subset$Time)
house.subset$DateTime_as_DT <- strptime(house.subset$DateTime, "%d/%m/%Y %H:%M:%S")
png(file = "plot3.png")
plot(house.subset$DateTime_as_DT, house.subset$Sub_metering_1, type="l", ylab = "Energy sub metering", xlab = "")
lines(house.subset$DateTime_as_DT, house.subset$Sub_metering_2, col = "Red")
lines(house.subset$DateTime_as_DT, house.subset$Sub_metering_3, col = "Blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("Black", "Red", "Blue"), lty = c(1,1,1))
dev.off()